// Generated by https://quicktype.io

import 'package:desgram_ui/domain/models/image_content_model.dart';
import 'package:desgram_ui/domain/models/partial_user_model.dart';
import 'package:flutter/material.dart';
import 'package:json_annotation/json_annotation.dart';

part 'post_model.g.dart';

@JsonSerializable()
class PostModel {
  String id;
  PartialUserModel user;
  String description;
  int? amountLikes;
  int? amountComments;
  bool isCommentsEnabled;
  bool hasLiked;
  DateTime createdDate;
  List<ImageContentModel> imageContents;

  PostModel({
    required this.id,
    required this.user,
    required this.description,
    required this.amountLikes,
    required this.amountComments,
    required this.isCommentsEnabled,
    required this.createdDate,
    required this.imageContents,
    required this.hasLiked,
  });

  factory PostModel.fromJson(Map<String, dynamic> json) =>
      _$PostModelFromJson(json);

  Map<String, dynamic> toJson() => _$PostModelToJson(this);
}
